schema_version = "1.0.0"
# https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html#manifest
id = "my_example_extension"
version = "1.5.0"
name = "Rock Generator"
tagline = "Adds a mesh rock to the Add Mesh menu"
maintainer = "RUben Begalov@gmail.com"
type = "add-on"
website = "https://github.com/Begalov/Rock-Generator"
tags = ["Add Mesh", "Modeling", "Object"]
blender_version_min = "3.6.0"
blender_version_max = "5.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2011 Paul Marshall",
  "Florian Felix",
  "Alexander Gavrilov",
  "2019 Jay Versluis",
  "2026 RUben Begalov@gmail.com",
]